engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
          python_version: 3
  fixme:
    enabled: true
  radon:
    enabled: true
    threshold: "C"
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - src/kpop/tests/