language: python
cache: pip
sudo: false

# Prepare environment
env:
  - CPATH=$HOME/.local/include
  - LIBRARY_PATH=$HOME/.local/lib
  - LD_LIBRARY_PATH=$HOME/.local/lib
  - MPLBACKEND="agg"
  - MATPLOTLIBRC=$HOME/matplotlibrc


# Test environments
matrix:
  include:
   - env: TOXENV=py34
     python: 3.4
   - env: TOXENV=py35
     python: 3.5
   - env: TOXENV=py36
     python: 3.6


# Package installation
install:
  - echo "backend: Agg" > $HOME/matplotlibrc
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install tox codecov Cython


# Run tests
script:
  - tox


# Register code coverage in coveralls
after_success:
  - codecov